<?php

use Illuminate\Database\Seeder;

class ReplayMapsSeeding extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $replay_map = [
            [ 'name' => 'Andromeda',            'url'=> 'storage/image/replay/map/Andromeda.jpg'],
            [ 'name' => 'Arcadia II',           'url'=> 'storage/image/replay/map/Arcadia II.jpg'],
            [ 'name' => 'Arkanoid',             'url'=> 'storage/image/replay/map/Arkanoid.jpg'],
            [ 'name' => 'Athena 2',             'url'=> 'storage/image/replay/map/Athena 2.jpg'],
            [ 'name' => 'Avan-garde II',        'url'=> 'storage/image/replay/map/Avan-garde II.jpg'],
            [ 'name' => 'Azalea',               'url'=> 'storage/image/replay/map/Azalea.jpg'],
            [ 'name' => 'Back And Belly',       'url'=> 'storage/image/replay/map/Back And Belly.jpg'],
            [ 'name' => 'Bifrost',              'url'=> 'storage/image/replay/map/Bifrost.jpg'],
            [ 'name' => 'Blade Storm',          'url'=> 'storage/image/replay/map/Blade Storm.jpg'],
            [ 'name' => 'Blue Storm',           'url'=> 'storage/image/replay/map/Blue Storm.jpg'],
            [ 'name' => 'Byzantium 2',          'url'=> 'storage/image/replay/map/Byzantium 2.jpg'],
            [ 'name' => 'Charity',              'url'=> 'storage/image/replay/map/Charity.jpg'],
            [ 'name' => 'Colosseum',            'url'=> 'storage/image/replay/map/Colosseum.jpg'],
            [ 'name' => 'Colosseum II',         'url'=> 'storage/image/replay/map/Colosseum II.jpg'],
            [ 'name' => 'Coulee',               'url'=> 'storage/image/replay/map/Coulee.jpg'],
            [ 'name' => 'Crystal Fire',         'url'=> 'storage/image/replay/map/Crystal Fire.jpg'],
            [ 'name' => 'Dahlia of Jungle',     'url'=> 'storage/image/replay/map/Dahlia of Jungle.jpg'],
            [ 'name' => 'Dark Sauron',          'url'=> 'storage/image/replay/map/Dark Sauron.jpg'],
            [ 'name' => 'Destination',          'url'=> 'storage/image/replay/map/Destination.jpg'],
            [ 'name' => 'Detonation',           'url'=> 'storage/image/replay/map/Detonation.jpg'],
            [ 'name' => 'Dire Straits',         'url'=> 'storage/image/replay/map/Dire Straits.jpg'],
            [ 'name' => 'Dream of Balhae',      'url'=> 'storage/image/replay/map/Dream of Balhae.jpg'],
            [ 'name' => 'Emperor of Emperor',   'url'=> 'storage/image/replay/map/Emperor of Emperor.jpg'],
            [ 'name' => 'Enter The Dragon',     'url'=> 'storage/image/replay/map/Enter The Dragon.jpg'],
            [ 'name' => 'Estrella',             'url'=> 'storage/image/replay/map/Estrella.jpg'],
            [ 'name' => 'Ever Forte',           'url'=> 'storage/image/replay/map/Ever Forte.jpg'],
            [ 'name' => 'Evolution WarpGate',   'url'=> 'storage/image/replay/map/Evolution WarpGate.jpg'],
            [ 'name' => 'Eye in the SKY',       'url'=> 'storage/image/replay/map/Eye in the SKY.jpg'],
            [ 'name' => 'Forbidden City',       'url'=> 'storage/image/replay/map/Forbidden City.jpg'],
            [ 'name' => 'Forbidden Zone',       'url'=> 'storage/image/replay/map/Forbidden Zone.jpg'],
            [ 'name' => 'Forest of Abyss',      'url'=> 'storage/image/replay/map/Forest of Abyss.jpg'],
            [ 'name' => 'Gaema Gowon',          'url'=> 'storage/image/replay/map/Gaema Gowon.jpg'],
            [ 'name' => 'Gaia',                 'url'=> 'storage/image/replay/map/Gaia.jpg'],
            [ 'name' => 'Gauntlet2003',         'url'=> 'storage/image/replay/map/Gauntlet2003.jpg'],
            [ 'name' => 'GauntletTG',           'url'=> 'storage/image/replay/map/GauntletTG.jpg'],
            [ 'name' => 'Gorky Island',         'url'=> 'storage/image/replay/map/Gorky Island.jpg'],
            [ 'name' => 'Guillotine',           'url'=> 'storage/image/replay/map/Guillotine.jpg'],
            [ 'name' => 'Hall of Valhalla',     'url'=> 'storage/image/replay/map/Hall of Valhalla.jpg'],
            [ 'name' => 'Hall of Valhalla V2',  'url'=> 'storage/image/replay/map/Hall of Valhalla V2.jpg'],
            [ 'name' => 'Hunters',              'url'=> 'storage/image/replay/map/Hunters.jpg'],
            [ 'name' => 'Huntress',             'url'=> 'storage/image/replay/map/Huntress.jpg'],
            [ 'name' => 'Hwangsanbul',          'url'=> 'storage/image/replay/map/Hwangsanbul.jpg'],
            [ 'name' => 'Incubus',              'url'=> 'storage/image/replay/map/Incubus.jpg'],
            [ 'name' => 'Incubus 2004',         'url'=> 'storage/image/replay/map/Incubus 2004.jpg'],
            [ 'name' => 'Indian Lament',        'url'=> 'storage/image/replay/map/Indian Lament.jpg'],
            [ 'name' => 'Into the Darkness',    'url'=> 'storage/image/replay/map/Into the Darkness.jpg'],
            [ 'name' => 'Isles of Siren',       'url'=> 'storage/image/replay/map/Isles of Siren.jpg'],
            [ 'name' => 'JRs Memory',           'url'=> 'storage/image/replay/map/JRs Memory.jpg'],
            [ 'name' => 'Jungle Story',         'url'=> 'storage/image/replay/map/Jungle Story.jpg'],
            [ 'name' => 'Jungle Story V2',      'url'=> 'storage/image/replay/map/Jungle Story V2.jpg'],
            [ 'name' => 'Katrina',              'url'=> 'storage/image/replay/map/Katrina.jpg'],
            [ 'name' => 'Katrina SE',           'url'=> 'storage/image/replay/map/Katrina SE.jpg'],
            [ 'name' => 'Korhal of Ceres',      'url'=> 'storage/image/replay/map/Korhal of Ceres.jpg'],
            [ 'name' => 'Labyrinth',            'url'=> 'storage/image/replay/map/Labyrinth.jpg'],
            [ 'name' => 'Legacy of Char',       'url'=> 'storage/image/replay/map/Legacy of Char.jpg'],
            [ 'name' => 'Longinus',             'url'=> 'storage/image/replay/map/Longinus.jpg'],
            [ 'name' => 'Lost Temple',          'url'=> 'storage/image/replay/map/Lost Temple.jpg'],
            [ 'name' => 'Luna',                 'url'=> 'storage/image/replay/map/Luna.jpg'],
            [ 'name' => 'Martian Cross',        'url'=> 'storage/image/replay/map/Martian Cross.jpg'],
            [ 'name' => 'Medusa',               'url'=> 'storage/image/replay/map/Medusa.jpg'],
            [ 'name' => 'Mercury',              'url'=> 'storage/image/replay/map/Mercury.jpg'],
            [ 'name' => 'Namja Iyagi',          'url'=> 'storage/image/replay/map/Namja Iyagi.jpg'],
            [ 'name' => 'NoName',               'url'=> 'storage/image/replay/map/NoName.jpg'],
            [ 'name' => 'Nostalgia',            'url'=> 'storage/image/replay/map/Nostalgia.jpg'],
            [ 'name' => 'Odin',                 'url'=> 'storage/image/replay/map/Odin.jpg'],
            [ 'name' => 'Othello',              'url'=> 'storage/image/replay/map/Othello.jpg'],
            [ 'name' => 'Paradoxxx1.0',         'url'=> 'storage/image/replay/map/Paradoxxx1.0.jpg'],
            [ 'name' => 'Paradoxxx2.0',         'url'=> 'storage/image/replay/map/Paradoxxx2.0.jpg'],
            [ 'name' => 'Parallel Lines 3',     'url'=> 'storage/image/replay/map/Parallel Lines 3.jpg'],
            [ 'name' => 'Paranoid Android',     'url'=> 'storage/image/replay/map/Paranoid Android.jpg'],
            [ 'name' => 'Pelennor',             'url'=> 'storage/image/replay/map/Pelennor.jpg'],
            [ 'name' => 'Plasma',               'url'=> 'storage/image/replay/map/Plasma.jpg'],
            [ 'name' => 'Pyth0n',               'url'=> 'storage/image/replay/map/Pyth0n.jpg'],
            [ 'name' => 'R-Point',              'url'=> 'storage/image/replay/map/R-Point.jpg'],
            [ 'name' => 'Raid Assault',         'url'=> 'storage/image/replay/map/Raid Assault.jpg'],
            [ 'name' => 'Remote Outpost',       'url'=> 'storage/image/replay/map/Remote Outpost.jpg'],
            [ 'name' => 'Requiem',              'url'=> 'storage/image/replay/map/Requiem.jpg'],
            [ 'name' => 'Return of the King',   'url'=> 'storage/image/replay/map/Return of the King.jpg'],
            [ 'name' => 'Ride of Valkryies',    'url'=> 'storage/image/replay/map/Ride of Valkryies.jpg'],
            [ 'name' => 'Rivalry',              'url'=> 'storage/image/replay/map/Rivalry.jpg'],
            [ 'name' => 'River of Flames',      'url'=> 'storage/image/replay/map/River of Flames.jpg'],
            [ 'name' => 'Shinhan bakdu 2.4',    'url'=> 'storage/image/replay/map/Shinhan bakdu 2.4.jpg'],
            [ 'name' => 'Silent Vortex',        'url'=> 'storage/image/replay/map/Silent Vortex.jpg'],
            [ 'name' => 'Sin Pioneer Period',   'url'=> 'storage/image/replay/map/Sin Pioneer Period.jpg'],
            [ 'name' => 'Snowbound',            'url'=> 'storage/image/replay/map/Snowbound.jpg'],
            [ 'name' => 'So1 815',              'url'=> 'storage/image/replay/map/So1 815.jpg'],
            [ 'name' => 'Symmetry of Psy',      'url'=> 'storage/image/replay/map/Symmetry of Psy.jpg'],
            [ 'name' => 'Tau Cross',            'url'=> 'storage/image/replay/map/Tau Cross.jpg'],
            [ 'name' => 'Tucson',               'url'=> 'storage/image/replay/map/Tucson.jpg'],
            [ 'name' => 'U-Boat',               'url'=> 'storage/image/replay/map/U-Boat.jpg'],
            [ 'name' => 'Universal Tripod',     'url'=> 'storage/image/replay/map/Universal Tripod.jpg'],
            [ 'name' => 'Valley of Wind',       'url'=> 'storage/image/replay/map/Valley of Wind.jpg'],
            [ 'name' => 'various',              'url'=> 'storage/image/replay/map/various.jpg'],
            [ 'name' => 'Vertigo',              'url'=> 'storage/image/replay/map/Vertigo.jpg'],
            [ 'name' => 'XenoSky',              'url'=> 'storage/image/replay/map/XenoSky.jpg'],
        ];

        \App\Models\ReplayMap::insert($replay_map);
    }
}
